import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar/navBar'
import SupabaseProvider from './supabase-provider'
import { SessionProvider } from './components/context/SessionContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <SupabaseProvider>
            <NavBar/>
            {children}
          </SupabaseProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
